# Generated by Django 5.1.15 on 2026-04-02 09:46

from django.db import migrations, models
from django.utils import timezone


def backfill_tos_accepted_at(apps, schema_editor):
    """Set tos_accepted_at for all existing users so they are not affected."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(tos_accepted_at__isnull=True).update(tos_accepted_at=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_replace_avatar_url_with_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tos_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_tos_accepted_at, migrations.RunPython.noop),
    ]
