# Generated by Django 5.1.15 on 2026-03-26 14:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("composer", "0003_idea"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes Requested"),
                            ("rejected", "Rejected"),
                            ("resubmitted", "Resubmitted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="approval_actions", to="composer.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "approvals_approval_action",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["post", "-created_at"], name="idx_approval_post_date")],
            },
        ),
        migrations.CreateModel(
            name="ApprovalReminder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stage", models.CharField(max_length=20)),
                ("reminder_count", models.PositiveIntegerField(default=0)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("escalated", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_reminders",
                        to="composer.post",
                    ),
                ),
            ],
            options={
                "db_table": "approvals_approval_reminder",
                "unique_together": {("post", "stage")},
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("body", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[("internal", "Internal"), ("external", "External")], default="external", max_length=10
                    ),
                ),
                ("attachment", models.ImageField(blank=True, null=True, upload_to="comment_attachments/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="approvals.postcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="composer.post"
                    ),
                ),
            ],
            options={
                "db_table": "approvals_post_comment",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["post", "created_at"], name="idx_comment_post_date"),
                    models.Index(fields=["post", "visibility"], name="idx_comment_post_vis"),
                ],
            },
        ),
    ]
