# Generated by Django 5.1.15 on 2026-06-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvalaction_platform_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalaction',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted'), ('held', 'Hold Requested')], max_length=20),
        ),
    ]
