# Generated by Django 5.1.15 on 2026-03-25 12:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgSetting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=255)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "settings_org_setting",
                "unique_together": {("organization", "key")},
            },
        ),
        migrations.CreateModel(
            name="WorkspaceSetting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=255)),
                ("value", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="settings", to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "db_table": "settings_workspace_setting",
                "unique_together": {("workspace", "key")},
            },
        ),
    ]
