# Generated by Django 5.1.15 on 2026-03-25 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calendar", "0001_initial"),
        ("social_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postingslot",
            name="social_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posting_slots",
                to="social_accounts.socialaccount",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postingslot",
            unique_together={("social_account", "day_of_week", "time")},
        ),
    ]
