# Generated by Django 5.1.15 on 2026-03-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0003_queue_queueentry_recurrencerule_customcalendarevent"),
        ("composer", "0004_contentcategory_post_category_csvimportjob_and_more"),
        ("social_accounts", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queues",
                to="composer.contentcategory",
            ),
        ),
        migrations.AddField(
            model_name="queue",
            name="social_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="queues", to="social_accounts.socialaccount"
            ),
        ),
        migrations.AddField(
            model_name="queue",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="queues", to="workspaces.workspace"
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="queue_entries", to="composer.post"
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="calendar.queue"
            ),
        ),
        migrations.AddField(
            model_name="recurrencerule",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="recurrence_rule", to="composer.post"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="queueentry",
            unique_together={("queue", "post")},
        ),
    ]
