# Generated by Django 5.1.15 on 2026-05-12 07:14

from django.db import migrations, models

import apps.common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0004_queue_category_queue_social_account_queue_workspace_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customcalendarevent",
            name="color",
            field=models.CharField(
                default="#3B82F6",
                help_text="Hex color for the event bar.",
                max_length=7,
                validators=[apps.common.validators.validate_hex_color],
            ),
        ),
    ]
