# Generated by Django 5.1.15 on 2026-05-22 07:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_organization_billing_email"),
        ("workspaces", "0003_alter_workspace_primary_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntelligenceSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("finalizing", "Finalizing"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                            ("provisioning_failed", "Provisioning failed"),
                        ],
                        db_index=True,
                        default="provisioning",
                        max_length=24,
                    ),
                ),
                ("plan_slug", models.SlugField(blank=True, default="", max_length=64)),
                ("stripe_customer_id", models.CharField(blank=True, default="", max_length=255)),
                ("stripe_subscription_id", models.CharField(blank=True, default="", max_length=255)),
                ("intelligence_account_id", models.CharField(blank=True, default="", max_length=64)),
                ("intelligence_api_key", apps.common.encryption.EncryptedTextField(blank=True, default="")),
                ("intelligence_api_key_prefix", models.CharField(blank=True, default="", max_length=8)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("provisioning_attempts", models.IntegerField(default=0)),
                ("last_provisioning_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_subscription",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_subscription",
            },
        ),
        migrations.CreateModel(
            name="PendingActivation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("session_id", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("rejected_unauthorized", "Rejected (unauthorized)"),
                            ("provisioning_failed", "Provisioning failed"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intelligence_pending_activations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_pending_activations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_pending_activation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntelligenceUsageEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("endpoint", models.CharField(max_length=64)),
                ("credits_charged", models.IntegerField(default=0)),
                ("status_code", models.IntegerField()),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_usage_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intelligence_usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intelligence_usage_events",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_usage_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "-created_at"], name="intelligenc_organiz_9c0731_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="StudioCheckoutAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("plan_slug", models.SlugField(max_length=64)),
                ("billing_email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("activated", "Activated"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        default="creating",
                        max_length=16,
                    ),
                ),
                ("stripe_session_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("checkout_url", models.URLField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_checkout_attempts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intelligence_checkout_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_studio_checkout_attempt",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["creating", "open", "pending"])),
                        fields=("organization",),
                        name="intel_studio_attempt_one_in_progress_per_org",
                    )
                ],
            },
        ),
    ]
