# Generated by Django 5.1.15 on 2026-03-25 17:28

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MastodonAppRegistration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("instance_url", models.URLField(max_length=500, unique=True)),
                ("client_id", apps.common.encryption.EncryptedTextField()),
                ("client_secret", apps.common.encryption.EncryptedTextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "social_accounts_mastodon_app_registration",
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("pinterest", "Pinterest"),
                            ("threads", "Threads"),
                            ("bluesky", "Bluesky"),
                            ("google_business", "Google Business Profile"),
                            ("mastodon", "Mastodon"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "account_platform_id",
                    models.CharField(help_text="The account's native ID on the platform.", max_length=255),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_handle", models.CharField(blank=True, default="", max_length=255)),
                ("avatar_url", models.URLField(blank=True, default="", max_length=500)),
                ("follower_count", models.IntegerField(default=0)),
                ("oauth_access_token", apps.common.encryption.EncryptedTextField(blank=True, default="")),
                ("oauth_refresh_token", apps.common.encryption.EncryptedTextField(blank=True, default="")),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("instance_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("token_expiring", "Token Expiring"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                        ],
                        default="connected",
                        max_length=20,
                    ),
                ),
                ("last_health_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "social_accounts_social_account",
                "unique_together": {("workspace", "platform", "account_platform_id")},
            },
        ),
    ]
