# Generated by Django 5.1.15 on 2026-04-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_accounts", "0002_split_linkedin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("instagram_personal", "Instagram (Personal)"),
                    ("linkedin_personal", "LinkedIn (Personal Profile)"),
                    ("linkedin_company", "LinkedIn (Company Page)"),
                    ("tiktok", "TikTok"),
                    ("youtube", "YouTube"),
                    ("pinterest", "Pinterest"),
                    ("threads", "Threads"),
                    ("bluesky", "Bluesky"),
                    ("google_business", "Google Business Profile"),
                    ("mastodon", "Mastodon"),
                ],
                max_length=30,
            ),
        ),
    ]
