# Generated by Django 5.1.15 on 2026-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_accounts", "0003_add_instagram_personal_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformVisibility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("instagram_personal", "Instagram (Personal)"),
                            ("linkedin_personal", "LinkedIn (Personal Profile)"),
                            ("linkedin_company", "LinkedIn (Company Page)"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("pinterest", "Pinterest"),
                            ("threads", "Threads"),
                            ("bluesky", "Bluesky"),
                            ("google_business", "Google Business Profile"),
                            ("mastodon", "Mastodon"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="If unchecked, this platform is hidden from the connect page."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Connect page platform",
                "verbose_name_plural": "Connect page platforms",
                "db_table": "social_accounts_platform_visibility",
                "ordering": ["platform"],
            },
        ),
    ]
