# Generated by Django 5.1.15 on 2026-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_accounts", "0007_increase_avatar_url_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="daily_post_limit_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
