/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppWorkspacesRouteImport } from './routes/_app.workspaces'
import { Route as AccountsLoginRouteImport } from './routes/accounts.login'
import { Route as AccountsSignupRouteImport } from './routes/accounts.signup'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AccountsPasswordForgotRouteImport } from './routes/accounts.password.forgot'
import { Route as AppOrganizationsOrgIdApiKeysRouteImport } from './routes/_app.organizations.$orgId.api-keys'
import { Route as AppOrganizationsOrgIdWorkspacesRouteImport } from './routes/_app.organizations.$orgId.workspaces'
import { Route as AppWorkspaceWorkspaceIdAnalyticsRouteImport } from './routes/_app.workspace.$workspaceId.analytics'
import { Route as AppWorkspaceWorkspaceIdApprovalsRouteImport } from './routes/_app.workspace.$workspaceId.approvals'
import { Route as AppWorkspaceWorkspaceIdCalendarRouteImport } from './routes/_app.workspace.$workspaceId.calendar'
import { Route as AppWorkspaceWorkspaceIdComposerRouteImport } from './routes/_app.workspace.$workspaceId.composer'
import { Route as AppWorkspaceWorkspaceIdInboxRouteImport } from './routes/_app.workspace.$workspaceId.inbox'
import { Route as AppWorkspaceWorkspaceIdMediaRouteImport } from './routes/_app.workspace.$workspaceId.media'
import { Route as AppWorkspaceWorkspaceIdMembersRouteImport } from './routes/_app.workspace.$workspaceId.members'
import { Route as AppWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_app.workspace.$workspaceId.settings'
import { Route as AppWorkspaceWorkspaceIdSocialAccountsRouteImport } from './routes/_app.workspace.$workspaceId.social-accounts'
import { Route as AccountsPasswordResetConfirmRouteImport } from './routes/accounts.password.reset.confirm'
import { Route as AppWorkspaceWorkspaceIdSettingsClientsRouteImport } from './routes/_app.workspace.$workspaceId.settings.clients'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AccountsLoginRoute = AccountsLoginRouteImport.update({
  id: '/accounts/login',
  path: '/accounts/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsSignupRoute = AccountsSignupRouteImport.update({
  id: '/accounts/signup',
  path: '/accounts/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsPasswordForgotRoute = AccountsPasswordForgotRouteImport.update({
  id: '/accounts/password/forgot',
  path: '/accounts/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsOrgIdApiKeysRoute =
  AppOrganizationsOrgIdApiKeysRouteImport.update({
    id: '/organizations/$orgId/api-keys',
    path: '/organizations/$orgId/api-keys',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsOrgIdWorkspacesRoute =
  AppOrganizationsOrgIdWorkspacesRouteImport.update({
    id: '/organizations/$orgId/workspaces',
    path: '/organizations/$orgId/workspaces',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdAnalyticsRoute =
  AppWorkspaceWorkspaceIdAnalyticsRouteImport.update({
    id: '/workspace/$workspaceId/analytics',
    path: '/workspace/$workspaceId/analytics',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdApprovalsRoute =
  AppWorkspaceWorkspaceIdApprovalsRouteImport.update({
    id: '/workspace/$workspaceId/approvals',
    path: '/workspace/$workspaceId/approvals',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdCalendarRoute =
  AppWorkspaceWorkspaceIdCalendarRouteImport.update({
    id: '/workspace/$workspaceId/calendar',
    path: '/workspace/$workspaceId/calendar',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdComposerRoute =
  AppWorkspaceWorkspaceIdComposerRouteImport.update({
    id: '/workspace/$workspaceId/composer',
    path: '/workspace/$workspaceId/composer',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdInboxRoute =
  AppWorkspaceWorkspaceIdInboxRouteImport.update({
    id: '/workspace/$workspaceId/inbox',
    path: '/workspace/$workspaceId/inbox',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdMediaRoute =
  AppWorkspaceWorkspaceIdMediaRouteImport.update({
    id: '/workspace/$workspaceId/media',
    path: '/workspace/$workspaceId/media',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdMembersRoute =
  AppWorkspaceWorkspaceIdMembersRouteImport.update({
    id: '/workspace/$workspaceId/members',
    path: '/workspace/$workspaceId/members',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdSettingsRoute =
  AppWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/workspace/$workspaceId/settings',
    path: '/workspace/$workspaceId/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceWorkspaceIdSocialAccountsRoute =
  AppWorkspaceWorkspaceIdSocialAccountsRouteImport.update({
    id: '/workspace/$workspaceId/social-accounts',
    path: '/workspace/$workspaceId/social-accounts',
    getParentRoute: () => AppRoute,
  } as any)
const AccountsPasswordResetConfirmRoute =
  AccountsPasswordResetConfirmRouteImport.update({
    id: '/accounts/password/reset/confirm',
    path: '/accounts/password/reset/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspaceWorkspaceIdSettingsClientsRoute =
  AppWorkspaceWorkspaceIdSettingsClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AppWorkspaceWorkspaceIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/accounts/login': typeof AccountsLoginRoute
  '/accounts/signup': typeof AccountsSignupRoute
  '/portal/$token': typeof PortalTokenRoute
  '/accounts/password/forgot': typeof AccountsPasswordForgotRoute
  '/organizations/$orgId/api-keys': typeof AppOrganizationsOrgIdApiKeysRoute
  '/organizations/$orgId/workspaces': typeof AppOrganizationsOrgIdWorkspacesRoute
  '/workspace/$workspaceId/analytics': typeof AppWorkspaceWorkspaceIdAnalyticsRoute
  '/workspace/$workspaceId/approvals': typeof AppWorkspaceWorkspaceIdApprovalsRoute
  '/workspace/$workspaceId/calendar': typeof AppWorkspaceWorkspaceIdCalendarRoute
  '/workspace/$workspaceId/composer': typeof AppWorkspaceWorkspaceIdComposerRoute
  '/workspace/$workspaceId/inbox': typeof AppWorkspaceWorkspaceIdInboxRoute
  '/workspace/$workspaceId/media': typeof AppWorkspaceWorkspaceIdMediaRoute
  '/workspace/$workspaceId/members': typeof AppWorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRouteWithChildren
  '/workspace/$workspaceId/social-accounts': typeof AppWorkspaceWorkspaceIdSocialAccountsRoute
  '/accounts/password/reset/confirm': typeof AccountsPasswordResetConfirmRoute
  '/workspace/$workspaceId/settings/clients': typeof AppWorkspaceWorkspaceIdSettingsClientsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/accounts/login': typeof AccountsLoginRoute
  '/accounts/signup': typeof AccountsSignupRoute
  '/portal/$token': typeof PortalTokenRoute
  '/accounts/password/forgot': typeof AccountsPasswordForgotRoute
  '/organizations/$orgId/api-keys': typeof AppOrganizationsOrgIdApiKeysRoute
  '/organizations/$orgId/workspaces': typeof AppOrganizationsOrgIdWorkspacesRoute
  '/workspace/$workspaceId/analytics': typeof AppWorkspaceWorkspaceIdAnalyticsRoute
  '/workspace/$workspaceId/approvals': typeof AppWorkspaceWorkspaceIdApprovalsRoute
  '/workspace/$workspaceId/calendar': typeof AppWorkspaceWorkspaceIdCalendarRoute
  '/workspace/$workspaceId/composer': typeof AppWorkspaceWorkspaceIdComposerRoute
  '/workspace/$workspaceId/inbox': typeof AppWorkspaceWorkspaceIdInboxRoute
  '/workspace/$workspaceId/media': typeof AppWorkspaceWorkspaceIdMediaRoute
  '/workspace/$workspaceId/members': typeof AppWorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRouteWithChildren
  '/workspace/$workspaceId/social-accounts': typeof AppWorkspaceWorkspaceIdSocialAccountsRoute
  '/accounts/password/reset/confirm': typeof AccountsPasswordResetConfirmRoute
  '/workspace/$workspaceId/settings/clients': typeof AppWorkspaceWorkspaceIdSettingsClientsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/accounts/login': typeof AccountsLoginRoute
  '/accounts/signup': typeof AccountsSignupRoute
  '/portal/$token': typeof PortalTokenRoute
  '/accounts/password/forgot': typeof AccountsPasswordForgotRoute
  '/_app/organizations/$orgId/api-keys': typeof AppOrganizationsOrgIdApiKeysRoute
  '/_app/organizations/$orgId/workspaces': typeof AppOrganizationsOrgIdWorkspacesRoute
  '/_app/workspace/$workspaceId/analytics': typeof AppWorkspaceWorkspaceIdAnalyticsRoute
  '/_app/workspace/$workspaceId/approvals': typeof AppWorkspaceWorkspaceIdApprovalsRoute
  '/_app/workspace/$workspaceId/calendar': typeof AppWorkspaceWorkspaceIdCalendarRoute
  '/_app/workspace/$workspaceId/composer': typeof AppWorkspaceWorkspaceIdComposerRoute
  '/_app/workspace/$workspaceId/inbox': typeof AppWorkspaceWorkspaceIdInboxRoute
  '/_app/workspace/$workspaceId/media': typeof AppWorkspaceWorkspaceIdMediaRoute
  '/_app/workspace/$workspaceId/members': typeof AppWorkspaceWorkspaceIdMembersRoute
  '/_app/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRouteWithChildren
  '/_app/workspace/$workspaceId/social-accounts': typeof AppWorkspaceWorkspaceIdSocialAccountsRoute
  '/accounts/password/reset/confirm': typeof AccountsPasswordResetConfirmRoute
  '/_app/workspace/$workspaceId/settings/clients': typeof AppWorkspaceWorkspaceIdSettingsClientsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/workspaces'
    | '/accounts/login'
    | '/accounts/signup'
    | '/portal/$token'
    | '/accounts/password/forgot'
    | '/organizations/$orgId/api-keys'
    | '/organizations/$orgId/workspaces'
    | '/workspace/$workspaceId/analytics'
    | '/workspace/$workspaceId/approvals'
    | '/workspace/$workspaceId/calendar'
    | '/workspace/$workspaceId/composer'
    | '/workspace/$workspaceId/inbox'
    | '/workspace/$workspaceId/media'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/social-accounts'
    | '/accounts/password/reset/confirm'
    | '/workspace/$workspaceId/settings/clients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/workspaces'
    | '/accounts/login'
    | '/accounts/signup'
    | '/portal/$token'
    | '/accounts/password/forgot'
    | '/organizations/$orgId/api-keys'
    | '/organizations/$orgId/workspaces'
    | '/workspace/$workspaceId/analytics'
    | '/workspace/$workspaceId/approvals'
    | '/workspace/$workspaceId/calendar'
    | '/workspace/$workspaceId/composer'
    | '/workspace/$workspaceId/inbox'
    | '/workspace/$workspaceId/media'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/social-accounts'
    | '/accounts/password/reset/confirm'
    | '/workspace/$workspaceId/settings/clients'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/onboarding'
    | '/_app/workspaces'
    | '/accounts/login'
    | '/accounts/signup'
    | '/portal/$token'
    | '/accounts/password/forgot'
    | '/_app/organizations/$orgId/api-keys'
    | '/_app/organizations/$orgId/workspaces'
    | '/_app/workspace/$workspaceId/analytics'
    | '/_app/workspace/$workspaceId/approvals'
    | '/_app/workspace/$workspaceId/calendar'
    | '/_app/workspace/$workspaceId/composer'
    | '/_app/workspace/$workspaceId/inbox'
    | '/_app/workspace/$workspaceId/media'
    | '/_app/workspace/$workspaceId/members'
    | '/_app/workspace/$workspaceId/settings'
    | '/_app/workspace/$workspaceId/social-accounts'
    | '/accounts/password/reset/confirm'
    | '/_app/workspace/$workspaceId/settings/clients'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccountsLoginRoute: typeof AccountsLoginRoute
  AccountsSignupRoute: typeof AccountsSignupRoute
  PortalTokenRoute: typeof PortalTokenRoute
  AccountsPasswordForgotRoute: typeof AccountsPasswordForgotRoute
  AccountsPasswordResetConfirmRoute: typeof AccountsPasswordResetConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/accounts/login': {
      id: '/accounts/login'
      path: '/accounts/login'
      fullPath: '/accounts/login'
      preLoaderRoute: typeof AccountsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/signup': {
      id: '/accounts/signup'
      path: '/accounts/signup'
      fullPath: '/accounts/signup'
      preLoaderRoute: typeof AccountsSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/password/forgot': {
      id: '/accounts/password/forgot'
      path: '/accounts/password/forgot'
      fullPath: '/accounts/password/forgot'
      preLoaderRoute: typeof AccountsPasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/organizations/$orgId/api-keys': {
      id: '/_app/organizations/$orgId/api-keys'
      path: '/organizations/$orgId/api-keys'
      fullPath: '/organizations/$orgId/api-keys'
      preLoaderRoute: typeof AppOrganizationsOrgIdApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/$orgId/workspaces': {
      id: '/_app/organizations/$orgId/workspaces'
      path: '/organizations/$orgId/workspaces'
      fullPath: '/organizations/$orgId/workspaces'
      preLoaderRoute: typeof AppOrganizationsOrgIdWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/analytics': {
      id: '/_app/workspace/$workspaceId/analytics'
      path: '/workspace/$workspaceId/analytics'
      fullPath: '/workspace/$workspaceId/analytics'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/approvals': {
      id: '/_app/workspace/$workspaceId/approvals'
      path: '/workspace/$workspaceId/approvals'
      fullPath: '/workspace/$workspaceId/approvals'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/calendar': {
      id: '/_app/workspace/$workspaceId/calendar'
      path: '/workspace/$workspaceId/calendar'
      fullPath: '/workspace/$workspaceId/calendar'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/composer': {
      id: '/_app/workspace/$workspaceId/composer'
      path: '/workspace/$workspaceId/composer'
      fullPath: '/workspace/$workspaceId/composer'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdComposerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/inbox': {
      id: '/_app/workspace/$workspaceId/inbox'
      path: '/workspace/$workspaceId/inbox'
      fullPath: '/workspace/$workspaceId/inbox'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/media': {
      id: '/_app/workspace/$workspaceId/media'
      path: '/workspace/$workspaceId/media'
      fullPath: '/workspace/$workspaceId/media'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/members': {
      id: '/_app/workspace/$workspaceId/members'
      path: '/workspace/$workspaceId/members'
      fullPath: '/workspace/$workspaceId/members'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/settings': {
      id: '/_app/workspace/$workspaceId/settings'
      path: '/workspace/$workspaceId/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/social-accounts': {
      id: '/_app/workspace/$workspaceId/social-accounts'
      path: '/workspace/$workspaceId/social-accounts'
      fullPath: '/workspace/$workspaceId/social-accounts'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSocialAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/accounts/password/reset/confirm': {
      id: '/accounts/password/reset/confirm'
      path: '/accounts/password/reset/confirm'
      fullPath: '/accounts/password/reset/confirm'
      preLoaderRoute: typeof AccountsPasswordResetConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace/$workspaceId/settings/clients': {
      id: '/_app/workspace/$workspaceId/settings/clients'
      path: '/clients'
      fullPath: '/workspace/$workspaceId/settings/clients'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSettingsClientsRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdSettingsRoute
    }
  }
}

interface AppWorkspaceWorkspaceIdSettingsRouteChildren {
  AppWorkspaceWorkspaceIdSettingsClientsRoute: typeof AppWorkspaceWorkspaceIdSettingsClientsRoute
}

const AppWorkspaceWorkspaceIdSettingsRouteChildren: AppWorkspaceWorkspaceIdSettingsRouteChildren =
  {
    AppWorkspaceWorkspaceIdSettingsClientsRoute:
      AppWorkspaceWorkspaceIdSettingsClientsRoute,
  }

const AppWorkspaceWorkspaceIdSettingsRouteWithChildren =
  AppWorkspaceWorkspaceIdSettingsRoute._addFileChildren(
    AppWorkspaceWorkspaceIdSettingsRouteChildren,
  )

interface AppRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppOrganizationsOrgIdApiKeysRoute: typeof AppOrganizationsOrgIdApiKeysRoute
  AppOrganizationsOrgIdWorkspacesRoute: typeof AppOrganizationsOrgIdWorkspacesRoute
  AppWorkspaceWorkspaceIdAnalyticsRoute: typeof AppWorkspaceWorkspaceIdAnalyticsRoute
  AppWorkspaceWorkspaceIdApprovalsRoute: typeof AppWorkspaceWorkspaceIdApprovalsRoute
  AppWorkspaceWorkspaceIdCalendarRoute: typeof AppWorkspaceWorkspaceIdCalendarRoute
  AppWorkspaceWorkspaceIdComposerRoute: typeof AppWorkspaceWorkspaceIdComposerRoute
  AppWorkspaceWorkspaceIdInboxRoute: typeof AppWorkspaceWorkspaceIdInboxRoute
  AppWorkspaceWorkspaceIdMediaRoute: typeof AppWorkspaceWorkspaceIdMediaRoute
  AppWorkspaceWorkspaceIdMembersRoute: typeof AppWorkspaceWorkspaceIdMembersRoute
  AppWorkspaceWorkspaceIdSettingsRoute: typeof AppWorkspaceWorkspaceIdSettingsRouteWithChildren
  AppWorkspaceWorkspaceIdSocialAccountsRoute: typeof AppWorkspaceWorkspaceIdSocialAccountsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppOrganizationsOrgIdApiKeysRoute: AppOrganizationsOrgIdApiKeysRoute,
  AppOrganizationsOrgIdWorkspacesRoute: AppOrganizationsOrgIdWorkspacesRoute,
  AppWorkspaceWorkspaceIdAnalyticsRoute: AppWorkspaceWorkspaceIdAnalyticsRoute,
  AppWorkspaceWorkspaceIdApprovalsRoute: AppWorkspaceWorkspaceIdApprovalsRoute,
  AppWorkspaceWorkspaceIdCalendarRoute: AppWorkspaceWorkspaceIdCalendarRoute,
  AppWorkspaceWorkspaceIdComposerRoute: AppWorkspaceWorkspaceIdComposerRoute,
  AppWorkspaceWorkspaceIdInboxRoute: AppWorkspaceWorkspaceIdInboxRoute,
  AppWorkspaceWorkspaceIdMediaRoute: AppWorkspaceWorkspaceIdMediaRoute,
  AppWorkspaceWorkspaceIdMembersRoute: AppWorkspaceWorkspaceIdMembersRoute,
  AppWorkspaceWorkspaceIdSettingsRoute:
    AppWorkspaceWorkspaceIdSettingsRouteWithChildren,
  AppWorkspaceWorkspaceIdSocialAccountsRoute:
    AppWorkspaceWorkspaceIdSocialAccountsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccountsLoginRoute: AccountsLoginRoute,
  AccountsSignupRoute: AccountsSignupRoute,
  PortalTokenRoute: PortalTokenRoute,
  AccountsPasswordForgotRoute: AccountsPasswordForgotRoute,
  AccountsPasswordResetConfirmRoute: AccountsPasswordResetConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
