# Generated by Django 5.1.15 on 2026-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_05b4bc_idx",
            old_name="notificatio_user_id_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_f2ad08_idx",
            old_name="notificatio_user_id_is_read_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationdelivery",
            new_name="notificatio_status_14083a_idx",
            old_name="notificatio_status_next_retry_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("post_submitted", "Post submitted for approval"),
                    ("post_approved", "Post approved"),
                    ("post_changes_requested", "Post changes requested"),
                    ("post_rejected", "Post rejected"),
                    ("post_published", "Post published"),
                    ("post_failed", "Post failed"),
                    ("new_inbox_message", "New inbox message"),
                    ("inbox_sla_overdue", "Inbox SLA overdue"),
                    ("client_approval_requested", "Client approval requested"),
                    ("team_member_invited", "Team member invited"),
                    ("social_account_disconnected", "Social account disconnected"),
                    ("report_generated", "Report generated"),
                    ("engagement_alert", "Engagement alert"),
                    ("client_connected_accounts", "Client connected accounts"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("post_submitted", "Post submitted for approval"),
                    ("post_approved", "Post approved"),
                    ("post_changes_requested", "Post changes requested"),
                    ("post_rejected", "Post rejected"),
                    ("post_published", "Post published"),
                    ("post_failed", "Post failed"),
                    ("new_inbox_message", "New inbox message"),
                    ("inbox_sla_overdue", "Inbox SLA overdue"),
                    ("client_approval_requested", "Client approval requested"),
                    ("team_member_invited", "Team member invited"),
                    ("social_account_disconnected", "Social account disconnected"),
                    ("report_generated", "Report generated"),
                    ("engagement_alert", "Engagement alert"),
                    ("client_connected_accounts", "Client connected accounts"),
                ],
                max_length=50,
            ),
        ),
    ]
