# Generated by Django 5.1.15 on 2026-03-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_rename_notificatio_user_id_created_idx_notificatio_user_id_05b4bc_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("post_submitted", "Post submitted for approval"),
                    ("post_approved", "Post approved"),
                    ("post_changes_requested", "Post changes requested"),
                    ("post_rejected", "Post rejected"),
                    ("post_published", "Post published"),
                    ("post_failed", "Post failed"),
                    ("new_inbox_message", "New inbox message"),
                    ("inbox_sla_overdue", "Inbox SLA overdue"),
                    ("client_approval_requested", "Client approval requested"),
                    ("team_member_invited", "Team member invited"),
                    ("social_account_disconnected", "Social account disconnected"),
                    ("report_generated", "Report generated"),
                    ("engagement_alert", "Engagement alert"),
                    ("comment_mention", "Mentioned in a comment"),
                    ("approval_reminder", "Approval reminder"),
                    ("approval_stalled", "Stalled approval escalation"),
                    ("client_connected_accounts", "Client connected accounts"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("post_submitted", "Post submitted for approval"),
                    ("post_approved", "Post approved"),
                    ("post_changes_requested", "Post changes requested"),
                    ("post_rejected", "Post rejected"),
                    ("post_published", "Post published"),
                    ("post_failed", "Post failed"),
                    ("new_inbox_message", "New inbox message"),
                    ("inbox_sla_overdue", "Inbox SLA overdue"),
                    ("client_approval_requested", "Client approval requested"),
                    ("team_member_invited", "Team member invited"),
                    ("social_account_disconnected", "Social account disconnected"),
                    ("report_generated", "Report generated"),
                    ("engagement_alert", "Engagement alert"),
                    ("comment_mention", "Mentioned in a comment"),
                    ("approval_reminder", "Approval reminder"),
                    ("approval_stalled", "Stalled approval escalation"),
                    ("client_connected_accounts", "Client connected accounts"),
                ],
                max_length=50,
            ),
        ),
    ]
