import { describe, expect, it } from "vitest";

import {
  hmacHex,
  issueApiKey,
  makeLookup,
  parseToken,
  verifyToken,
} from "./api-key.crypto";

process.env.SECRET_KEY = "test-secret-key-migration-fixture";
process.env.ENCRYPTION_KEY_SALT = "test-salt-migration-fixture";

/**
 * Vectors generated by the LEGACY Python implementation
 * (apps/api_keys/services.py: _hmac_hex/_make_lookup) with the env vars above.
 * If these break, every existing bb_studio_ key stops working after cutover.
 */
const PYTHON_HMAC = "b8c03925167f7a68dff5b9d43956411afdd4bfe1586eea71f2d1ee25cfe9925c";
const PYTHON_LOOKUP = "84d168a1";
const RANDOM_PART = "fixture-random-part-123";

describe("ApiKey crypto (byte-compat with apps/api_keys/services.py)", () => {
  it("computes the same HMAC and lookup as the legacy Python code", () => {
    expect(hmacHex(RANDOM_PART)).toBe(PYTHON_HMAC);
    expect(makeLookup(RANDOM_PART)).toBe(PYTHON_LOOKUP);
  });

  it("issues keys in the bb_studio_<random>_<lookup8> format", () => {
    const key = issueApiKey();
    expect(key.raw.startsWith("bb_studio_")).toBe(true);
    const parsed = parseToken(key.raw)!;
    expect(parsed.lookupPrefix).toBe(key.lookupPrefix);
    expect(verifyToken(key.raw, key.tokenHash)).toBe(true);
  });

  it("parses tokens whose secret contains underscores (rsplit on last _)", () => {
    const raw = "bb_studio_a_b_c-d_e-verylongsecret_1a2b3c4d";
    const parsed = parseToken(raw)!;
    expect(parsed.randomPart).toBe("a_b_c-d_e-verylongsecret");
    expect(parsed.lookupPrefix).toBe("1a2b3c4d");
  });

  it("rejects malformed tokens", () => {
    expect(parseToken("wrong_prefix_x_y")).toBeNull();
    expect(parseToken("bb_studio_noseparator")).toBeNull();
    expect(parseToken("bb_studio_secret_short7")).toBeNull(); // lookup must be 8 chars
    expect(parseToken(undefined)).toBeNull();
    expect(verifyToken("garbage", PYTHON_HMAC)).toBe(false);
  });
});
