# Generated by Django 5.1.15 on 2026-03-25 12:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("icon_url", models.URLField(blank=True, default="")),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("timezone", models.CharField(blank=True, default="", max_length=63)),
                ("primary_color", models.CharField(blank=True, default="", max_length=7)),
                ("secondary_color", models.CharField(blank=True, default="", max_length=7)),
                ("default_hashtags", models.JSONField(blank=True, default=list)),
                ("default_first_comment", models.TextField(blank=True, default="")),
                (
                    "approval_workflow_mode",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("optional", "Optional"),
                            ("required_internal", "Required (Internal)"),
                            ("required_internal_and_client", "Required (Internal + Client)"),
                        ],
                        default="none",
                        max_length=40,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "workspaces_workspace",
            },
        ),
    ]
