# Generated by Django 5.1.15 on 2026-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="icon_url",
        ),
        migrations.AddField(
            model_name="workspace",
            name="icon",
            field=models.ImageField(blank=True, upload_to="workspaces/icons/%Y/%m/"),
        ),
    ]
