# Generated by Django 5.1.15 on 2026-05-12 07:14

from django.db import migrations, models

import apps.common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_replace_icon_url_with_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="primary_color",
            field=models.CharField(
                blank=True, default="", max_length=7, validators=[apps.common.validators.validate_hex_color]
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="secondary_color",
            field=models.CharField(
                blank=True, default="", max_length=7, validators=[apps.common.validators.validate_hex_color]
            ),
        ),
    ]
