# Generated by Django 5.1.15 on 2026-05-30 07:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "key",
                    models.CharField(
                        help_text="Client-chosen idempotency key (free-form string, max 128 chars).", max_length=128
                    ),
                ),
                (
                    "request_fingerprint",
                    models.CharField(
                        help_text="SHA-256 of (method + path + canonical body); guards against key reuse with a different body.",
                        max_length=64,
                    ),
                ),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to="api_keys.apikey",
                    ),
                ),
            ],
            options={
                "db_table": "agent_api_idempotency",
                "indexes": [models.Index(fields=["created_at"], name="idx_idem_created_at")],
                "unique_together": {("api_key", "key")},
            },
        ),
    ]
