# Generated by Django 5.1.15 on 2026-03-26 14:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("composer", "0003_idea"),
        ("social_accounts", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("platform_message_id", models.CharField(db_index=True, max_length=255)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("mention", "Mention"),
                            ("dm", "Direct Message"),
                            ("review", "Review"),
                        ],
                        db_index=True,
                        default="comment",
                        max_length=20,
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                ("sender_handle", models.CharField(blank=True, default="", max_length=255)),
                ("sender_avatar_url", models.URLField(blank=True, default="", max_length=500)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "sentiment",
                    models.CharField(
                        choices=[("positive", "Positive"), ("neutral", "Neutral"), ("negative", "Negative")],
                        db_index=True,
                        default="neutral",
                        max_length=10,
                    ),
                ),
                (
                    "sentiment_source",
                    models.CharField(choices=[("auto", "Auto"), ("manual", "Manual")], default="auto", max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="unread",
                        max_length=10,
                    ),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_inbox_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_replies",
                        to="inbox.inboxmessage",
                    ),
                ),
                (
                    "related_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbox_messages",
                        to="composer.platformpost",
                    ),
                ),
                (
                    "social_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_messages",
                        to="social_accounts.socialaccount",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_messages",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "inbox_message",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="InboxReply",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("body", models.TextField()),
                ("platform_reply_id", models.CharField(blank=True, default="", max_length=255)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbox_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inbox_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="replies", to="inbox.inboxmessage"
                    ),
                ),
            ],
            options={
                "db_table": "inbox_reply",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="InboxSLAConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_response_minutes", models.PositiveIntegerField(default=120)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "auto_resolve_on_reply",
                    models.BooleanField(
                        default=True, help_text="Automatically mark messages as resolved when a reply is sent."
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_sla_config",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "inbox_sla_config",
            },
        ),
        migrations.CreateModel(
            name="InternalNote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbox_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inbox_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_notes",
                        to="inbox.inboxmessage",
                    ),
                ),
            ],
            options={
                "db_table": "inbox_internal_note",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedReply",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(help_text="Supports variables: {sender_name}, {account_name}, {post_url}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_saved_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_replies",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "inbox_saved_reply",
                "ordering": ["title"],
            },
        ),
        migrations.AddIndex(
            model_name="inboxmessage",
            index=models.Index(fields=["workspace", "status", "-received_at"], name="inbox_msg_ws_status_recv"),
        ),
        migrations.AddIndex(
            model_name="inboxmessage",
            index=models.Index(fields=["workspace", "assigned_to", "status"], name="inbox_msg_ws_assign_status"),
        ),
        migrations.AddIndex(
            model_name="inboxmessage",
            index=models.Index(
                fields=["workspace", "social_account", "-received_at"], name="inbox_msg_ws_account_recv"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inboxmessage",
            unique_together={("social_account", "platform_message_id")},
        ),
    ]
