# Generated by Django 5.1.15 on 2026-03-25 13:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("platform_specific_caption", models.TextField(blank=True, null=True)),
                (
                    "platform_specific_media",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of media asset IDs with platform-specific ordering/cropping.",
                        null=True,
                    ),
                ),
                ("platform_specific_first_comment", models.TextField(blank=True, null=True)),
                (
                    "platform_post_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The post ID on the platform after publishing.",
                        max_length=255,
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("publish_error", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "composer_platform_post",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("caption", models.TextField(blank=True, default="")),
                ("first_comment", models.TextField(blank=True, default="")),
                ("internal_notes", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("pending_client", "Pending Client"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes Requested"),
                            ("rejected", "Rejected"),
                            ("scheduled", "Scheduled"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("partially_published", "Partially Published"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "composer_post",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField(default=0, help_text="Ordering position in carousel.")),
                ("alt_text", models.TextField(blank=True, default="")),
                (
                    "platform_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Per-platform crop/format overrides, e.g. {"instagram": {"crop": "4:5"}}',
                    ),
                ),
            ],
            options={
                "db_table": "composer_post_media",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="PostVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_number", models.PositiveIntegerField()),
                (
                    "snapshot",
                    models.JSONField(help_text="Full post state at time of save (caption, media, platforms, etc.)."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "composer_post_version",
                "ordering": ["-version_number"],
            },
        ),
    ]
