# Generated by Django 5.1.15 on 2026-03-25 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("composer", "0001_initial"),
        ("media_library", "0001_initial"),
        ("social_accounts", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="platformpost",
            name="social_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platform_posts",
                to="social_accounts.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="workspaces.workspace"
            ),
        ),
        migrations.AddField(
            model_name="platformpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="platform_posts", to="composer.post"
            ),
        ),
        migrations.AddField(
            model_name="postmedia",
            name="media_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="post_usages", to="media_library.mediaasset"
            ),
        ),
        migrations.AddField(
            model_name="postmedia",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="media_attachments", to="composer.post"
            ),
        ),
        migrations.AddField(
            model_name="postversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="postversion",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="composer.post"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status", "scheduled_at"], name="idx_post_status_sched"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["workspace", "status"], name="idx_post_ws_status"),
        ),
        migrations.AlterUniqueTogether(
            name="platformpost",
            unique_together={("post", "social_account")},
        ),
        migrations.AlterUniqueTogether(
            name="postmedia",
            unique_together={("post", "media_asset")},
        ),
        migrations.AlterUniqueTogether(
            name="postversion",
            unique_together={("post", "version_number")},
        ),
    ]
