# Generated by Django 5.1.15 on 2026-03-26 14:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0003_idea"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", help_text="Hex color for calendar display, e.g. #FF5733", max_length=7
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_categories",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "content categories",
                "db_table": "composer_content_category",
                "ordering": ["position", "name"],
                "unique_together": {("workspace", "name")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="composer.contentcategory",
            ),
        ),
        migrations.CreateModel(
            name="CSVImportJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="csv_imports/")),
                ("column_mapping", models.JSONField(default=dict, help_text="Maps CSV column indices to post fields.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                (
                    "result_summary",
                    models.JSONField(default=dict, help_text='{"created": N, "errors": N, "warnings": [...]}'),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csv_import_jobs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "composer_csv_import_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "template_data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON snapshot: caption, first_comment, category_id, platform_ids, hashtags, media_asset_ids, tags",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_templates",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "composer_post_template",
                "ordering": ["name"],
            },
        ),
    ]
