# Generated by Django 5.1.15 on 2026-03-26 23:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0004_contentcategory_post_category_csvimportjob_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeaGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea_groups",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "composer_idea_group",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="idea",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ideas",
                to="composer.ideagroup",
            ),
        ),
    ]
