# Generated by Django 5.1.15 on 2026-03-27 00:03

from django.db import migrations

DEFAULT_GROUPS = [
    ("Unassigned", "unassigned", 0),
    ("To Do", "todo", 1),
    ("In Progress", "in_progress", 2),
    ("Done", "done", 3),
]


def populate_groups(apps, schema_editor):
    """Create default IdeaGroups for every workspace that has ideas,
    and assign each idea to the matching group based on its status."""
    IdeaGroup = apps.get_model("composer", "IdeaGroup")
    Idea = apps.get_model("composer", "Idea")

    workspace_ids = Idea.objects.values_list("workspace_id", flat=True).distinct()

    for ws_id in workspace_ids:
        status_to_group = {}
        for name, status_key, position in DEFAULT_GROUPS:
            grp = IdeaGroup.objects.create(
                workspace_id=ws_id,
                name=name,
                position=position,
            )
            status_to_group[status_key] = grp

        for idea in Idea.objects.filter(workspace_id=ws_id):
            idea.group = status_to_group.get(idea.status)
            idea.save(update_fields=["group"])


def reverse_groups(apps, schema_editor):
    IdeaGroup = apps.get_model("composer", "IdeaGroup")
    IdeaGroup.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0005_add_idea_group"),
    ]

    operations = [
        migrations.RunPython(populate_groups, reverse_groups),
    ]
