# Generated by Django 5.1.15 on 2026-03-30 09:00

from django.db import migrations


def populate_tags(apps, schema_editor):
    """Create Tag records from existing JSONField tags on Posts and Ideas."""
    Tag = apps.get_model("composer", "Tag")
    Post = apps.get_model("composer", "Post")
    Idea = apps.get_model("composer", "Idea")

    # Collect all unique (workspace_id, tag_name) pairs
    seen = set()
    tags_to_create = []

    for model_cls in (Post, Idea):
        for obj in model_cls.objects.exclude(tags=[]).exclude(tags__isnull=True):
            for tag_name in obj.tags:
                key = (obj.workspace_id, tag_name)
                if key not in seen:
                    seen.add(key)
                    tags_to_create.append(Tag(workspace_id=obj.workspace_id, name=tag_name))

    if tags_to_create:
        Tag.objects.bulk_create(tags_to_create, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0008_add_tag_model"),
    ]

    operations = [
        migrations.RunPython(populate_tags, migrations.RunPython.noop),
    ]
