# Generated by Django 5.1.15 on 2026-03-30 11:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0009_populate_tags_from_json"),
        ("workspaces", "0002_replace_icon_url_with_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(help_text="RSS feed URL", max_length=500)),
                ("website_url", models.URLField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="feeds", to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "db_table": "composer_feed",
                "ordering": ["name"],
                "unique_together": {("workspace", "url")},
            },
        ),
    ]
