# Generated by Django 5.1.15 on 2026-03-30 23:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


def _backfill_idea_media(apps, schema_editor):
    Idea = apps.get_model("composer", "Idea")
    IdeaMedia = apps.get_model("composer", "IdeaMedia")

    rows = []
    for idea in Idea.objects.exclude(media_asset_id__isnull=True).only("id", "media_asset_id").iterator():
        rows.append(
            IdeaMedia(
                id=uuid.uuid4(),
                idea_id=idea.id,
                media_asset_id=idea.media_asset_id,
                position=0,
            )
        )

    if rows:
        IdeaMedia.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0011_add_media_asset_to_idea"),
        ("media_library", "0002_mediaasset_is_starred_mediaasset_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeaMedia",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField(default=0, help_text="Ordering position on the idea.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_attachments",
                        to="composer.idea",
                    ),
                ),
                (
                    "media_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea_attachments",
                        to="media_library.mediaasset",
                    ),
                ),
            ],
            options={
                "db_table": "composer_idea_media",
                "ordering": ["position", "created_at"],
                "unique_together": {("idea", "media_asset")},
            },
        ),
        migrations.RunPython(_backfill_idea_media, migrations.RunPython.noop),
    ]
