# Generated by Django 5.1.15 on 2026-05-12 07:14

from django.db import migrations, models

import apps.common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0015_per_account_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcategory",
            name="color",
            field=models.CharField(
                default="#3B82F6",
                help_text="Hex color for calendar display, e.g. #FF5733",
                max_length=7,
                validators=[apps.common.validators.validate_hex_color],
            ),
        ),
    ]
