# Generated by Django 5.1.15 on 2026-06-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0016_alter_contentcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='proposed_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
