# Generated by Django 5.1.15 on 2026-06-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0017_post_proposed_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_client', 'Pending Client'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('on_hold', 'On Hold')], db_index=True, default='draft', max_length=30),
        ),
    ]
