# Generated by Django 5.1.15 on 2026-06-30 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0018_alter_platformpost_status"),
        ("composer", "0018_normalize_facebook_platform_post_ids"),
    ]

    operations = []
