# Generated by Django 5.1.15 on 2026-06-01 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("composer", "0016_alter_contentcategory_color"),
        ("social_accounts", "0010_seed_analytics_platform_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountInsightsSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_key", models.CharField(max_length=40)),
                ("date", models.DateField()),
                ("value", models.FloatField(default=0.0)),
                ("captured_at", models.DateTimeField(auto_now=True)),
                (
                    "social_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to="social_accounts.socialaccount",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_account_insights_snapshot",
                "indexes": [
                    models.Index(fields=["social_account", "metric_key", "date"], name="analytics_a_social__834db1_idx")
                ],
                "unique_together": {("social_account", "metric_key", "date")},
            },
        ),
        migrations.CreateModel(
            name="PostInsightsSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_key", models.CharField(max_length=40)),
                ("date", models.DateField()),
                ("value", models.FloatField(default=0.0)),
                ("captured_at", models.DateTimeField(auto_now=True)),
                (
                    "platform_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to="composer.platformpost",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_post_insights_snapshot",
                "indexes": [
                    models.Index(fields=["platform_post", "metric_key", "date"], name="analytics_p_platfor_205698_idx"),
                    models.Index(fields=["platform_post", "date"], name="analytics_p_platfor_288b36_idx"),
                ],
                "unique_together": {("platform_post", "metric_key", "date")},
            },
        ),
    ]
