# Generated by Django 5.1.15 on 2026-03-25 13:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="media_library/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video"), ("gif", "GIF"), ("document", "Document")],
                        max_length=20,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("file_size", models.PositiveBigIntegerField(default=0, help_text="File size in bytes.")),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("duration", models.FloatField(default=0, help_text="Video duration in seconds.")),
                ("thumbnail", models.ImageField(blank=True, upload_to="media_library/thumbs/%Y/%m/")),
                ("alt_text", models.TextField(blank=True, default="")),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", help_text="e.g., 'upload', 'unsplash', 'pexels'", max_length=50
                    ),
                ),
                ("source_url", models.URLField(blank=True, default="")),
                ("attribution", models.TextField(blank=True, default="")),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "processed_variants",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dict of platform-specific processed versions: {'instagram': {'file': 'path', 'width': 1080}}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "media_library_media_asset",
                "ordering": ["-created_at"],
            },
        ),
    ]
