# Generated by Django 5.1.15 on 2026-06-15 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_mediaasset_is_starred_mediaasset_organization_and_more'),
        ('organizations', '0002_organization_billing_email'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('declared_content_type', models.CharField(blank=True, default='', max_length=100)),
                ('declared_filename', models.CharField(max_length=255)),
                ('max_bytes', models.PositiveBigIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_uploads', to=settings.AUTH_USER_MODEL)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to='organizations.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'media_library_pending_upload',
                'indexes': [models.Index(fields=['expires_at', 'finalized_at'], name='media_libra_expires_491541_idx')],
            },
        ),
    ]
