# Generated by Django 5.1.15 on 2026-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="billing_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
