"""
Built-in post templates - content prompts and starting points.

Each template is a dict with: id, emoji, title, description, category, color.
Optional: body (the fill-in-the-blank template text), tags (list of tag strings).
Colors are CSS rgb strings used for the card accent.
"""

CATEGORIES = [
    {"slug": "all", "label": "All", "icon": "layout-grid"},
    {"slug": "tip", "label": "Tip", "icon": "lightbulb"},
    {"slug": "case-study", "label": "Case Study", "icon": "scroll-text"},
    {"slug": "story", "label": "Story", "icon": "book-open"},
    {"slug": "how-to", "label": "How-to", "icon": "pickaxe"},
    {"slug": "question", "label": "Question", "icon": "message-circle-question"},
    {"slug": "opinion", "label": "Opinion", "icon": "quote"},
    {"slug": "list", "label": "List", "icon": "clipboard-list"},
    {"slug": "behind-the-scenes", "label": "Behind the Scenes", "icon": "clapperboard"},
]

# Six rotating accent colors (rgb strings)
COLORS = [
    "255, 203, 49",  # yellow
    "218, 255, 53",  # lime
    "99, 117, 255",  # indigo
    "248, 149, 151",  # pink
    "87, 152, 255",  # blue
    "59, 252, 255",  # cyan
]

FEATURED_IDS = [20, 44, 3]

TEMPLATES = [
    {
        "id": 161,
        "emoji": "\U0001f9e9",
        "title": "Break this down step by step",
        "description": "Turn a complicated concept into clear, scannable steps anyone can follow.",
        "body": "Most people overcomplicate {{topic}}. Here's how it actually works:\n\nStep 1: {{first action}}\nStep 2: {{second action}}\nStep 3: {{third action}}\n\nThat's it. No fancy tools, no complex setup. Just {{core benefit}}.",
        "tags": ["Educational", "How-to"],
        "category": "how-to",
        "color": COLORS[0],
    },
    {
        "id": 160,
        "emoji": "\U0001f4d8",
        "title": "Teach one clear takeaway",
        "description": "Distill a focused insight your audience can put to work today.",
        "body": "One thing I wish I knew earlier about {{topic}}:\n\n{{the insight, one or two sentences}}.\n\nWhy it matters: {{explain the impact in practical terms}}.\n\nTry this today: {{one specific action they can take right now}}.",
        "tags": ["Tip", "Value"],
        "category": "tip",
        "color": COLORS[1],
    },
    {
        "id": 159,
        "emoji": "\U0001f9ea",
        "title": "Show a product or process in action",
        "description": "Walk through how something works using a specific, real scenario.",
        "body": "Let me show you how {{product/process}} works in practice.\n\nThe situation: {{describe the real scenario or problem}}.\n\nWhat I did: {{walk through the steps you took}}.\n\nThe result: {{concrete outcome or metric}}.\n\nIf you're dealing with {{similar problem}}, this might help.",
        "tags": ["Case Study", "How-to"],
        "category": "how-to",
        "color": COLORS[2],
    },
    {
        "id": 158,
        "emoji": "\U0001f3af",
        "title": "Who this is for (and who it's not)",
        "description": "Draw a clear line around who your product, service, or content is designed for.",
        "body": "This is for you if:\n\u2022 You're {{description of person or stage}}\n\u2022 You've been struggling with {{pain point}}\n\u2022 You want {{desired outcome}} without {{common frustration}}\n\nThis is NOT for you if:\n\u2022 You're looking for {{what you don't offer}}\n\u2022 You already have {{thing they wouldn't need}}\n\nClarity saves everyone time. Send this to someone who needs it.",
        "tags": ["Tip", "Positioning"],
        "category": "tip",
        "color": COLORS[3],
    },
    {
        "id": 157,
        "emoji": "\U0001f4c8",
        "title": "Document your progress",
        "description": "Show momentum without needing a big win or a polished metric.",
        "body": "Quick update on {{project or goal}}:\n\nWhere I started: {{starting point}}.\nWhere I am now: {{current state}}.\nWhat I'm learning: {{key insight or surprise}}.\n\nNo highlight reel. Just progress. What are you working on right now?",
        "tags": ["Behind the Scenes", "Authenticity"],
        "category": "behind-the-scenes",
        "color": COLORS[4],
    },
    {
        "id": 156,
        "emoji": "\U0001fa9e",
        "title": "Make your audience feel seen",
        "description": "Reflect a common thought or struggle your audience quietly deals with.",
        "body": "Nobody talks about the part where {{common hidden struggle}}.\n\nThe part where you {{relatable feeling or experience}}.\n\nIf that's you right now, here's what I want you to know: {{encouraging truth or reframe}}.\n\nYou're not behind. You're in it.",
        "tags": ["Empathy", "Community"],
        "category": "question",
        "color": COLORS[5],
    },
    {
        "id": 155,
        "emoji": "\U0001f9ed",
        "title": "Narrowing my content focus",
        "description": "Declare what you want to be known for right now and drop the noise.",
        "body": "I'm simplifying what I post about.\n\nFrom now on, I'm focused on:\n\u2022 {{Topic 1}}\n\u2022 {{Topic 2}}\n\u2022 {{Topic 3}}\n\nWhat I'm dropping: {{things you're cutting}}.\n\nTrying to cover everything made me {{consequence}}. Going deep on fewer things beats going wide on all of them.",
        "tags": ["Strategy", "Reflection"],
        "category": "tip",
        "color": COLORS[0],
    },
    {
        "id": 140,
        "emoji": "\U0001f680",
        "title": "I told myself I couldn't do it",
        "description": "Tell the story of trying something you thought was out of reach. What made you start, and what surprised you?",
        "body": "6 months ago, I told myself: \"I'll never be able to {{big goal}}.\"\n\nWhat changed: {{the trigger or decision that shifted things}}.\n\nThe hardest part wasn't {{expected difficulty}}. It was {{unexpected challenge}}.\n\nBut here I am. {{Where you are now}}.\n\nIf you've been sitting on {{similar leap}}, just start.",
        "tags": ["Story", "Motivation"],
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 139,
        "emoji": "\u2753",
        "title": "What's your best tip for [challenge]?",
        "description": "Ask your audience to share their go-to strategy, tool, or habit for something you're working on.",
        "body": "I'm working on {{challenge}} and could use your brain for a second.\n\nWhat's one thing that's helped you with {{specific aspect of the challenge}}?\n\nA tool? A habit? A different way of thinking about it?\n\nDrop your best tip below. I'll share my favorites later this week.",
        "tags": ["Engagement", "Question"],
        "category": "question",
        "color": COLORS[4],
    },
    {
        "id": 138,
        "emoji": "\U0001f342",
        "title": "Monthly goals",
        "description": "Put your creative, business, or personal goals for the month on paper and invite your audience to do the same.",
        "body": "Here's what I'm focusing on this month:\n\n1. {{Goal 1}}\n2. {{Goal 2}}\n3. {{Goal 3}}\n\nLast month's win: {{something you accomplished}}.\nThis month's stretch: {{your ambitious target}}.\n\nWhat's on your list? Drop it below.",
        "tags": ["Community", "Goals"],
        "category": "list",
        "color": COLORS[5],
    },
    {
        "id": 137,
        "emoji": "\U0001f383",
        "title": "Scarier than ghosting",
        "description": "A fun, relatable list that ties seasonal humor to consistency.",
        "category": "list",
        "color": COLORS[0],
    },
    {
        "id": 136,
        "emoji": "\U0001f383",
        "title": "That time I ghosted...",
        "description": "Tell a story about a time you didn't follow through and what you took away from it.",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 135,
        "emoji": "\U0001f383",
        "title": "3 ways to avoid ghosting",
        "description": "Quick, practical tips to help your audience stay on top of industry-specific commitments this season.",
        "category": "tip",
        "color": COLORS[2],
    },
    {
        "id": 134,
        "emoji": "\U0001f383",
        "title": "Behind the scenes of not ghosting",
        "description": "Show your process for staying consistent with content during a packed October.",
        "category": "behind-the-scenes",
        "color": COLORS[3],
    },
    {
        "id": 133,
        "emoji": "\U0001f383",
        "title": "What's scarier?",
        "description": "Spark conversation with a seasonal 'would you rather' style question.",
        "category": "question",
        "color": COLORS[4],
    },
    {
        "id": 132,
        "emoji": "\U0001f4ac",
        "title": "Ask me anything",
        "description": "Invite your audience to ask you questions about your journey, work, or area of focus.",
        "category": "question",
        "color": COLORS[5],
    },
    {
        "id": 131,
        "emoji": "\u267b\ufe0f",
        "title": "If I had to rebuild from zero",
        "description": "No shortcuts, no network. Walk through the first 3 steps you'd take and ask your audience what they'd do differently.",
        "category": "opinion",
        "color": COLORS[0],
    },
    {
        "id": 130,
        "emoji": "\U0001f3af",
        "title": "How I got [result] without [expected method]",
        "description": "Break down a recent win and the unconventional path you took to get there.",
        "category": "case-study",
        "color": COLORS[1],
    },
    {
        "id": 129,
        "emoji": "\U0001f4ad",
        "title": "The biggest mindset shift I made this year",
        "description": "One belief, perspective, or routine that changed how you approach your work or creativity.",
        "category": "story",
        "color": COLORS[2],
    },
    {
        "id": 128,
        "emoji": "\u2728",
        "title": "How I find ideas when nothing's working",
        "description": "Your go-to rituals, tools, or habits for finding creativity again when you're stuck.",
        "category": "tip",
        "color": COLORS[3],
    },
    {
        "id": 109,
        "emoji": "\u2705",
        "title": "My back-to-school checklist",
        "description": "The personal, professional, or business habits and tools you're prioritizing this season.",
        "category": "list",
        "color": COLORS[5],
    },
    {
        "id": 108,
        "emoji": "\U0001f4dd",
        "title": "Report card for the year so far",
        "description": "Borrow the school report card format. Grade yourself on progress toward your goals this year.",
        "category": "behind-the-scenes",
        "color": COLORS[0],
    },
    {
        "id": 107,
        "emoji": "\u270f\ufe0f",
        "title": "The assignment I'm giving myself",
        "description": "Frame a goal or habit as a homework assignment for accountability.",
        "category": "opinion",
        "color": COLORS[1],
    },
    {
        "id": 106,
        "emoji": "\U0001f392",
        "title": "Back-to-school essentials",
        "description": "The tools, apps, or habits you consider essential for kicking off a productive season.",
        "category": "list",
        "color": COLORS[2],
    },
    {
        "id": 105,
        "emoji": "\U0001f342",
        "title": "New season, new routine",
        "description": "How your daily routine is shifting as the season changes, like students adjusting back to school.",
        "category": "behind-the-scenes",
        "color": COLORS[3],
    },
    {
        "id": 103,
        "emoji": "\U0001f30e",
        "title": "The environment that fuels your creativity",
        "description": "Describe a place or setting that helps you think clearly or feel inspired.",
        "category": "behind-the-scenes",
        "color": COLORS[4],
    },
    {
        "id": 102,
        "emoji": "\U0001f5a5\ufe0f",
        "title": "Show your work setup",
        "description": "A snapshot of the space where you do your best work.",
        "category": "behind-the-scenes",
        "color": COLORS[5],
    },
    {
        "id": 101,
        "emoji": "\U0001f516",
        "title": "A quote that stuck with me",
        "description": "One line that's shaped your thinking. Tell the story around it.",
        "category": "opinion",
        "color": COLORS[0],
    },
    {
        "id": 99,
        "emoji": "\U0001f504",
        "title": "My midday reset ritual",
        "description": "The small habits or actions that help you refocus halfway through the day.",
        "category": "how-to",
        "color": COLORS[1],
    },
    {
        "id": 98,
        "emoji": "\U0001f319",
        "title": "How I wind down at night",
        "description": "How you disconnect, reflect, or prep for the next day after work.",
        "category": "behind-the-scenes",
        "color": COLORS[2],
    },
    {
        "id": 97,
        "emoji": "\u2600\ufe0f",
        "title": "My morning workflow",
        "description": "Walk your audience through a morning routine or work setup that keeps you productive.",
        "category": "how-to",
        "color": COLORS[3],
    },
    {
        "id": 96,
        "emoji": "\u2712\ufe0f",
        "title": "Introduce (or reintroduce) yourself",
        "description": "Tell your audience who you are, what you post about, and who it's for.",
        "category": "story",
        "color": COLORS[4],
    },
    {
        "id": 88,
        "emoji": "\U0001f4f0",
        "title": "5 newsletters I never miss",
        "description": "A curated list of high-value newsletters for your niche, with a line on why each one is worth it.",
        "category": "list",
        "color": COLORS[5],
    },
    {
        "id": 87,
        "emoji": "\U0001f501",
        "title": "One habit I swear by, and one I'm quitting",
        "description": "A personal contrast that invites your audience to do the same.",
        "category": "opinion",
        "color": COLORS[0],
    },
    {
        "id": 86,
        "emoji": "\u2696\ufe0f",
        "title": "Which one are you? [Option A] vs [Option B]",
        "description": "Use contrast to spark quick, decision-based interaction.",
        "category": "question",
        "color": COLORS[1],
    },
    {
        "id": 85,
        "emoji": "\u270d\ufe0f",
        "title": "Fill in the blank: I wish more people knew ___ about [topic]",
        "description": "A low-effort way to prompt thoughtful replies.",
        "category": "question",
        "color": COLORS[2],
    },
    {
        "id": 84,
        "emoji": "\U0001f643",
        "title": "Best advice you've ever ignored?",
        "description": "Spark conversation by sharing a personal 'I'm glad I didn't listen' moment.",
        "category": "question",
        "color": COLORS[3],
    },
    {
        "id": 83,
        "emoji": "\U0001f525",
        "title": "Unpopular opinion about [industry/topic]?",
        "description": "Invite bold responses and challenge the status quo in your field.",
        "category": "opinion",
        "color": COLORS[4],
    },
    {
        "id": 82,
        "emoji": "\U0001f634",
        "title": "This feature is slept on",
        "description": "Highlight an underrated feature of your product or offer that keeps delivering results.",
        "category": "tip",
        "color": COLORS[5],
    },
    {
        "id": 81,
        "emoji": "\u23f3",
        "title": "Why now's the time to try this",
        "description": "Position your offer or product as timely, tied to a trend or seasonal need.",
        "category": "tip",
        "color": COLORS[0],
    },
    {
        "id": 80,
        "emoji": "\u2753",
        "title": "The one question that changed my strategy",
        "description": "Sometimes one question shifts everything. What was the moment, the question, and how it reshaped your direction?",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 77,
        "emoji": "\U0001f502",
        "title": "What I wish I knew before starting my business",
        "description": "Looking back, what would you do differently? The lessons that would've saved you time, money, or stress.",
        "category": "tip",
        "color": COLORS[2],
    },
    {
        "id": 76,
        "emoji": "\u23f1\ufe0f",
        "title": "The system that saves me hours every week",
        "description": "One repeatable system that made your work faster or more scalable. Break it down so others can borrow it.",
        "category": "how-to",
        "color": COLORS[3],
    },
    {
        "id": 75,
        "emoji": "\U0001f4b2",
        "title": "How I'd launch a business with $500",
        "description": "Starting from scratch with a small budget. The tools, priorities, and decisions you'd make to get results without wasting a cent.",
        "category": "how-to",
        "color": COLORS[4],
    },
    {
        "id": 74,
        "emoji": "\U0001f645\U0001f3fe\u200d\u2642\ufe0f",
        "title": "One thing we stopped doing this year",
        "description": "What did you let go of? A client type, offer, or habit? The decision, the risk, and how it opened space for better results.",
        "category": "opinion",
        "color": COLORS[5],
    },
    {
        "id": 72,
        "emoji": "\U0001f635",
        "title": "When everything went wrong in one week",
        "description": "What broke, how you responded, and what you'd do differently next time. People relate to the messy parts.",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 71,
        "emoji": "\U0001f4c4",
        "title": "The offer nobody talks about (but always performs)",
        "description": "One service, product, or offer that quietly delivers great results. Why it works so well.",
        "category": "case-study",
        "color": COLORS[2],
    },
    {
        "id": 70,
        "emoji": "\U0001f3eb",
        "title": "One thing our clients taught us",
        "description": "Working with clients reveals what no strategy guide can. One surprising lesson that shifted how you deliver.",
        "category": "case-study",
        "color": COLORS[3],
    },
    {
        "id": 69,
        "emoji": "\U0001f4c8",
        "title": "Why we raised our prices",
        "description": "The thought process behind a price increase. What led to it, how you communicated it, and what happened after.",
        "category": "case-study",
        "color": COLORS[4],
    },
    {
        "id": 68,
        "emoji": "\U0001f4c5",
        "title": "What happened in our business this month",
        "description": "A look back at the last 30 days. What went right, what didn't, and what you took away from it.",
        "category": "behind-the-scenes",
        "color": COLORS[5],
    },
    {
        "id": 67,
        "emoji": "\U0001f3c6",
        "title": "One small shift that made a big difference this month",
        "description": "A tool, habit, or tweak that helped you or your team. No major overhaul, just one thing that worked.",
        "category": "tip",
        "color": COLORS[0],
    },
    {
        "id": 66,
        "emoji": "\U0001f504",
        "title": "The mistake we kept making",
        "description": "The recurring mistake you repeated, and the shift that finally broke the cycle.",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 61,
        "emoji": "\U0001f62c",
        "title": "The mistake I can't forget",
        "description": "A cringeworthy or painful mistake and what it taught you. Normalize learning out loud instead of pretending to be perfect.",
        "category": "story",
        "color": COLORS[2],
    },
    {
        "id": 60,
        "emoji": "\U0001f19a",
        "title": "How I handle things now vs. then",
        "description": "Show the gap between your past and present self, especially how you respond to challenges. What changed?",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 59,
        "emoji": "\U0001fa9e",
        "title": "When I realized I was faking confidence",
        "description": "The moment you recognized a behavior you thought was strength was actually fear. What shifted after you saw it?",
        "category": "story",
        "color": COLORS[4],
    },
    {
        "id": 58,
        "emoji": "\U0001f526",
        "title": "The moment I realized I was holding myself back",
        "description": "A situation that made you see you were playing it safe. What triggered the shift, and how did you grow from there?",
        "category": "story",
        "color": COLORS[5],
    },
    {
        "id": 57,
        "emoji": "\U0001f300",
        "title": "No 5-year plan, just progress",
        "description": "What happened when you stopped chasing a perfect roadmap and started following what felt aligned. What opened up?",
        "category": "opinion",
        "color": COLORS[0],
    },
    {
        "id": 56,
        "emoji": "\U0001f4e9",
        "title": "The message I still think about",
        "description": "A DM, an offhand comment, or a line from a mentor. The moment someone's words reshaped how you see your work.",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 55,
        "emoji": "\U0001f4b8",
        "title": "The expensive lesson I'm glad I learned",
        "description": "A hard-earned insight, financial or emotional, that cost you something but gave you clarity in return.",
        "category": "story",
        "color": COLORS[2],
    },
    {
        "id": 54,
        "emoji": "\U0001f9d7",
        "title": "A year ago, this would have terrified me",
        "description": "Reflect on something you once feared but now do comfortably. What changed?",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 53,
        "emoji": "\U0001f3af",
        "title": "The quiet shift that changed my direction",
        "description": "A subtle moment or realization that ended up changing your path in a big way.",
        "category": "story",
        "color": COLORS[4],
    },
    {
        "id": 52,
        "emoji": "\U0001f6ab",
        "title": "When ignoring advice paid off",
        "description": "One popular piece of advice you chose not to follow, and how going your own way led to growth.",
        "category": "opinion",
        "color": COLORS[5],
    },
    {
        "id": 51,
        "emoji": "\U0001f4cc",
        "title": "A step-by-step that actually works",
        "description": "Break down a simple, repeatable system that helped you reach a goal. Make it easy for others to follow.",
        "category": "how-to",
        "color": COLORS[0],
    },
    {
        "id": 50,
        "emoji": "\U0001f9e9",
        "title": "How I turned frustration into a system",
        "description": "A time you replaced a messy workflow with a clear process, and the results that came from it.",
        "category": "how-to",
        "color": COLORS[1],
    },
    {
        "id": 49,
        "emoji": "\u23f1\ufe0f",
        "title": "How I got results in 3 days",
        "description": "A time-bound challenge where you set a goal and hit it fast. The steps, and the result you didn't expect.",
        "category": "case-study",
        "color": COLORS[2],
    },
    {
        "id": 48,
        "emoji": "\U0001f501",
        "title": "The 3-step system I use every time",
        "description": "A task or problem you face often? The multi-step method you always return to, and why it holds up under pressure.",
        "category": "how-to",
        "color": COLORS[3],
    },
    {
        "id": 47,
        "emoji": "\U0001f4cb",
        "title": "My process, step by step",
        "description": "Your personal method for achieving a goal or solving a problem. Step by step, easy to follow and adapt.",
        "category": "how-to",
        "color": COLORS[4],
    },
    {
        "id": 46,
        "emoji": "\U0001f422",
        "title": "How slowing down made me more productive",
        "description": "What happened when you stopped pushing so hard and gave yourself space. How that pause helped you move faster.",
        "category": "story",
        "color": COLORS[5],
    },
    {
        "id": 45,
        "emoji": "\U0001f6e0\ufe0f",
        "title": "My honest review of a tool I tried",
        "description": "A transparent review of a tool, method, or platform you tested. What worked, what didn't, and who you'd recommend it to.",
        "category": "case-study",
        "color": COLORS[0],
    },
    {
        "id": 44,
        "emoji": "\U0001f501",
        "title": "A one-week experiment that changed everything",
        "description": "Tried something new for a week? What you changed, what you noticed, and whether you're keeping it.",
        "body": "I tried doing {{thing}} differently for a week, and it completely changed {{outcome}}.\n\nWhat I tried: I challenged myself to {{change behavior or habit}} for one week.\n\nWhat happened: Harder than I expected, but I started noticing {{small shifts or big wins}}.\n\nLesson: I'm keeping this one. It changed how I {{area}}.",
        "tags": ["Celebration", "Case Study"],
        "category": "case-study",
        "color": COLORS[1],
    },
    {
        "id": 43,
        "emoji": "\U0001f9ef",
        "title": "When good advice didn't work for me",
        "description": "A time you followed popular advice and it backfired, and what worked better for your situation.",
        "category": "opinion",
        "color": COLORS[2],
    },
    {
        "id": 42,
        "emoji": "\U0001f9ea",
        "title": "I tested it so you don't have to",
        "description": "A mini case study where you tried a tool, strategy, or habit. Honest results: what worked, what didn't, what you learned.",
        "category": "case-study",
        "color": COLORS[3],
    },
    {
        "id": 41,
        "emoji": "\U0001f6aa",
        "title": "I wasn't ready, so I started anyway",
        "description": "A time you started without having it all figured out. How action, not certainty, built the momentum you needed.",
        "category": "story",
        "color": COLORS[4],
    },
    {
        "id": 40,
        "emoji": "\U0001f50d",
        "title": "The detail everyone overlooks",
        "description": "One habit, detail, or mindset others skip over that you've found makes all the difference. Why it matters.",
        "category": "opinion",
        "color": COLORS[5],
    },
    {
        "id": 39,
        "emoji": "\u26a0\ufe0f",
        "title": "When 'best practices' failed me",
        "description": "A popular strategy or belief you tried, how it fell short, and what you did instead that worked.",
        "category": "opinion",
        "color": COLORS[0],
    },
    {
        "id": 38,
        "emoji": "\U0001f393",
        "title": "You can share before you're an expert",
        "description": "Tackle the myth that you need credentials to show up online. Your experience, even in progress, is still useful to others.",
        "category": "opinion",
        "color": COLORS[1],
    },
    {
        "id": 37,
        "emoji": "\U0001f504",
        "title": "Something I changed my mind about",
        "description": "A belief, habit, or opinion you no longer hold, and what shifted your perspective. Invite others to reflect on theirs.",
        "category": "opinion",
        "color": COLORS[2],
    },
    {
        "id": 36,
        "emoji": "\U0001f648",
        "title": "The worst advice I ever followed",
        "description": "A piece of advice or tool that totally backfired. The story, the outcome, and what you wish you'd done instead.",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 35,
        "emoji": "\U0001f552",
        "title": "Is this actually productive, or just popular?",
        "description": "Challenge a routine or belief that gets praised in your industry but doesn't deliver. Your experience, and ask others for theirs.",
        "category": "opinion",
        "color": COLORS[4],
    },
    {
        "id": 34,
        "emoji": "\U0001f4ac",
        "title": "One thing I'd change in my industry",
        "description": "A norm, habit, or mindset in your field that feels outdated. Your take, and an invitation for others to weigh in.",
        "category": "opinion",
        "color": COLORS[5],
    },
    {
        "id": 33,
        "emoji": "\u2753",
        "title": "Overrated or misunderstood?",
        "description": "Take a closer look at a trend, tool, or practice. Your experience, and the question: does it actually help, or is it hype?",
        "category": "question",
        "color": COLORS[0],
    },
    {
        "id": 32,
        "emoji": "\U0001f6e0\ufe0f",
        "title": "What to try when nothing's working",
        "description": "If you've hit a wall with a goal before, suggest a practical shift that worked for you.",
        "category": "tip",
        "color": COLORS[1],
    },
    {
        "id": 31,
        "emoji": "\U0001f9d0",
        "title": "The biggest misconception in my field",
        "description": "Something people consistently get wrong in your industry or niche. Clear it up and invite others to weigh in.",
        "category": "opinion",
        "color": COLORS[2],
    },
    {
        "id": 30,
        "emoji": "\u267b\ufe0f",
        "title": "Starting over today: my first 3 moves",
        "description": "Rebuilding from scratch, no shortcuts, no network. The first 3 steps you'd take, and what your audience would do differently.",
        "category": "opinion",
        "color": COLORS[3],
    },
    {
        "id": 29,
        "emoji": "\U0001f9ef",
        "title": "You don't need what you think you need",
        "description": "Challenge the myth that success requires a certain tool, degree, or habit. What actually moved the needle for you.",
        "category": "opinion",
        "color": COLORS[4],
    },
    {
        "id": 28,
        "emoji": "\U0001f525",
        "title": "Why I stopped following 'best practices'",
        "description": "A popular strategy or belief you've rejected, and what you do instead. Your reasoning, and how others approach it.",
        "category": "opinion",
        "color": COLORS[5],
    },
    {
        "id": 27,
        "emoji": "\U0001f4ca",
        "title": "When the data caught up to what you already knew",
        "description": "New stats or research that confirm a pattern you've seen firsthand. The case for action, and who should be paying attention.",
        "category": "case-study",
        "color": COLORS[0],
    },
    {
        "id": 26,
        "emoji": "\U0001f9e0",
        "title": "It's more than a new format",
        "description": "When a new tool or platform catches on, it often reflects a deeper shift. What you're noticing, and how you're adapting.",
        "category": "opinion",
        "color": COLORS[1],
    },
    {
        "id": 25,
        "emoji": "\U0001f4c8",
        "title": "A quiet shift that changes everything",
        "description": "A subtle behavior or pattern you've noticed that signals a bigger change. The trend, what it means, and how you're adapting.",
        "category": "opinion",
        "color": COLORS[2],
    },
    {
        "id": 24,
        "emoji": "\U0001f5e3\ufe0f",
        "title": "What nobody's saying about this trend",
        "description": "Take a trend that's everywhere and dig deeper. What are people missing, and what's the real insight under the hype?",
        "category": "opinion",
        "color": COLORS[3],
    },
    {
        "id": 23,
        "emoji": "\U0001f50d",
        "title": "What this trend actually means",
        "description": "A popular trend and what it signals about how people work, share, or connect. How you're responding to it.",
        "category": "opinion",
        "color": COLORS[4],
    },
    {
        "id": 22,
        "emoji": "\U0001f4c9",
        "title": "How I got stuck in the comparison trap",
        "description": "How comparing yourself to others slowed you down or warped your goals, and the shift that got you back on track.",
        "category": "story",
        "color": COLORS[5],
    },
    {
        "id": 21,
        "emoji": "\u23f3",
        "title": "I should've started sooner",
        "description": "A time perfectionism got in the way, and what finally helped you take action. Someone else might need that same nudge.",
        "category": "story",
        "color": COLORS[0],
    },
    {
        "id": 20,
        "emoji": "\U0001f4b8",
        "title": "I used to price on fear, not value",
        "description": "A time you underpriced your work out of fear or comparison, and how switching to value-based pricing changed your results.",
        "body": "Mistake: I set my prices based on {{self-doubt, comparison, fear, etc.}}.\n\nLesson: That led to {{overwork, burnout, lack of interest, etc.}}.\n\nAdvice: Now I use {{value-based pricing, transparent process, or qualification system}}.",
        "tags": ["Reflection", "Story"],
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 19,
        "emoji": "\U0001f6e0\ufe0f",
        "title": "The quick fix that made things worse",
        "description": "A time a shortcut or bandaid solution didn't work, and what longer-term approach actually solved the problem.",
        "category": "story",
        "color": COLORS[2],
    },
    {
        "id": 18,
        "emoji": "\U0001f9ef",
        "title": "It didn't go how I expected",
        "description": "A strategy or belief that completely backfired. What you expected, what happened, and what you'd do differently now.",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 17,
        "emoji": "\U0001f9d8",
        "title": "One small change that shifted everything",
        "description": "A situation that felt stuck and the small change in behavior or thinking that fixed it.",
        "category": "tip",
        "color": COLORS[4],
    },
    {
        "id": 16,
        "emoji": "\U0001f4c6",
        "title": "The system that saved me",
        "description": "A system, habit, or routine that helped you feel less scattered. The before and after difference it made.",
        "category": "how-to",
        "color": COLORS[5],
    },
    {
        "id": 15,
        "emoji": "\U0001f4a1",
        "title": "The obvious solution didn't work. This did.",
        "description": "A time you chased a common fix that didn't work, and the unexpected solution that made the difference.",
        "category": "story",
        "color": COLORS[0],
    },
    {
        "id": 14,
        "emoji": "\U0001f680",
        "title": "I never thought I could pull this off",
        "description": "Tell the story of trying something you thought was out of reach. What made you start, and what surprised you about the outcome?",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 13,
        "emoji": "\U0001f504",
        "title": "Before, during, after: what finally worked",
        "description": "Walk through a clear transformation. What you struggled with, what you tried, and what changed. Keep it real.",
        "category": "case-study",
        "color": COLORS[2],
    },
    {
        "id": 12,
        "emoji": "\U0001f3af",
        "title": "I almost didn't try it. Glad I did.",
        "description": "A moment of hesitation that turned into a breakthrough. What made you take the risk, and the outcome.",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 11,
        "emoji": "\U0001f9ed",
        "title": "I threw out the rulebook",
        "description": "A time you dropped a 'best practice' or common belief that wasn't serving you. What happened when you found your own way.",
        "category": "opinion",
        "color": COLORS[4],
    },
    {
        "id": 10,
        "emoji": "\U0001f5d3\ufe0f",
        "title": "How I structure my workweek",
        "description": "A peek at how you organize your week: meetings, deep work, creative time, or rest. It doesn't have to be perfect. Just real.",
        "category": "behind-the-scenes",
        "color": COLORS[5],
    },
    {
        "id": 9,
        "emoji": "\U0001f300",
        "title": "This content format works every time",
        "description": "A post format, prompt style, or idea type you keep returning to. The kind that consistently gets replies, shares, or saves.",
        "category": "tip",
        "color": COLORS[0],
    },
    {
        "id": 8,
        "emoji": "\U0001f3a7",
        "title": "My go-to playlist for focus or reset",
        "description": "A playlist or tracks that help you stay grounded, focused, or creatively recharged.",
        "category": "list",
        "color": COLORS[1],
    },
    {
        "id": 7,
        "emoji": "\u2709\ufe0f",
        "title": "The cold email that actually worked",
        "description": "Your go-to cold email format or script that got results. Break down why it worked and how others can tweak it.",
        "category": "how-to",
        "color": COLORS[2],
    },
    {
        "id": 6,
        "emoji": "\U0001f50d",
        "title": "Creators to follow in my niche",
        "description": "A curated list of people doing great work in your space. Why they're worth following and what you've picked up from them.",
        "category": "list",
        "color": COLORS[3],
    },
    {
        "id": 5,
        "emoji": "\U0001f6e0\ufe0f",
        "title": "My go-to tools for getting things done",
        "description": "The tools you rely on weekly. What they help you with, why you like them, and how they've changed your workflow.",
        "category": "list",
        "color": COLORS[4],
    },
    {
        "id": 4,
        "emoji": "\u26a1\ufe0f",
        "title": "How I stay productive without burning out",
        "description": "How you improved your focus without falling into hustle culture. What didn't work? What small change helped you get more done with less stress?",
        "category": "tip",
        "color": COLORS[5],
    },
    {
        "id": 3,
        "emoji": "\U0001f9e0",
        "title": "The fix was simpler than I thought",
        "description": "A problem you overcomplicated, and the simple solution that actually solved it. Help others skip the trial and error.",
        "body": "I thought I needed {{assumed solution}}. Turns out, I needed {{actual solution}}.\n\nWhen I faced {{problem}}, I thought the answer was obvious: {{assumed solution}}. But no matter how much I tried, it wasn't working.\n\nThen I switched to {{actual solution}}, and everything clicked. Now, {{describe the positive result}}.",
        "tags": ["Expertise", "Story"],
        "category": "tip",
        "color": COLORS[0],
    },
    {
        "id": 1,
        "emoji": "\U0001f4da",
        "title": "Books that changed how I work",
        "description": "A curated list of books that helped you level up in your career or craft, and why each one mattered.",
        "category": "list",
        "color": COLORS[1],
    },
]


def get_featured_templates():
    """Return the 3 featured templates."""
    by_id = {t["id"]: t for t in TEMPLATES}
    return [by_id[fid] for fid in FEATURED_IDS if fid in by_id]


def get_all_templates():
    """Return all templates."""
    return TEMPLATES
