# Generated by Django 5.1.15 on 2026-03-26 14:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.client_portal.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicLinkToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=apps.client_portal.models._generate_magic_token,
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(default=apps.client_portal.models._default_expiry)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_consumed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_link_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_link_tokens",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "client_portal_magic_link_token",
                "indexes": [models.Index(fields=["user", "workspace"], name="idx_magic_user_ws")],
            },
        ),
    ]
