# Generated by Django 5.1.15 on 2026-05-30 06:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("social_accounts", "0008_socialaccount_daily_post_limit_override"),
        ("workspaces", "0003_alter_workspace_primary_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text='Human label, e.g. "Zapier bot".', max_length=100)),
                ("lookup_prefix", models.CharField(db_index=True, max_length=16, unique=True)),
                ("token_hash", models.CharField(help_text="HMAC-SHA256 hex digest.", max_length=64)),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="List of permission keys the holder is granted (subset of PERMISSION_KEYS).",
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "rate_override_writes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Per-minute write-rate override. Null = use platform default.", null=True
                    ),
                ),
                (
                    "rate_override_reads",
                    models.PositiveIntegerField(
                        blank=True, help_text="Per-minute read-rate override. Null = use platform default.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who issued the key. If they lose membership the key dies on next use.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "social_accounts",
                    models.ManyToManyField(
                        help_text="Explicit allowlist of accounts this key may act on (size >= 1).",
                        related_name="api_keys",
                        to="social_accounts.socialaccount",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="api_keys", to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "db_table": "api_keys_api_key",
            },
        ),
        migrations.CreateModel(
            name="ApiKeyAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        help_text='Verb + resource, e.g. "post.create", "post.cancel", "accounts.list".', max_length=64
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the primary resource affected (Post, PlatformPost, ...).",
                        null=True,
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="api_keys.apikey"
                    ),
                ),
            ],
            options={
                "db_table": "api_keys_audit_log",
            },
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["workspace", "revoked_at"], name="idx_apikey_ws_revoked"),
        ),
        migrations.AddIndex(
            model_name="apikeyauditlog",
            index=models.Index(fields=["api_key", "created_at"], name="idx_audit_key_time"),
        ),
    ]
