# Generated by Django 5.1.15 on 2026-06-09 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_keys", "0002_backfill_view_analytics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apikeyauditlog",
            name="actor_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Credential type, e.g. "oauth". Empty for bb_studio_ keys.',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="apikeyauditlog",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for OAuth-authenticated MCP requests; null for key requests.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mcp_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apikeyauditlog",
            name="api_key",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for bb_studio_ key requests; null for OAuth callers (see actor_user).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="api_keys.apikey",
            ),
        ),
    ]
